# Generated by Django 5.0.1 on 2024-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='descricacao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='fila',
            old_name='nome',
            new_name='nome_fila',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_conclusao',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_prevista',
            field=models.DateField(blank=True),
        ),
    ]
