# Generated by Django 4.2.4 on 2024-02-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_alocacao_agendamento_alter_alocacao_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='agendamento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacao', to='api.agendamento'),
        ),
    ]
